allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  zeptomatch: false
  ngrok: false
  msgpackr-extract: false
  workerd: false
